spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: robortboss01@gmail.com
    password: 
    properties:
      mail:
        smtp:
          auth: true
          starttls:
              enable: true
